### ISSUE TITLE
Create a RESTful /parameters endpoint

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-api#100]
The basics are:

- Tested, including in CI.
- Lists parameters in `/parameters` as an object of IDs pointing to a subset of the associated properties.
- Gives all properties of a parameter in `/parameter/$ID`.

Details to be discussed:

- What is the subset to be presented in `/parameters`?
- Where does the country package metadata go?
- What are the contents of the `description` property?
- What are the names of the properties?

**Comment by fpagnoux** [comment]
Let's start discussing the route `beta.api.openfisca.fr/parameters`:

Based on what's __currently__ inside the `XML` parameter file, we could return something like:

**Exemple 1:**
```JSON
{
    "prestations.minima_sociaux.rsa.montant_de_base_du_rsa": {
        "description": "Minima sociaux ; Revenu de solidarité active ; Rsa socle"
    },
    "cotsoc.gen.smic_h_b": {
        "description": "Cotisations sociales ; Paramètres généraux ; SMIC horaire brut"
    }
}
```

*If we improve the description in the parameter file*, we could get something like :

**Exemple 2:**
```JSON
{
    "prestations.minima_sociaux.rsa.montant_de_base_du_rsa": {
        "description": "Montant de base du rsa socle"
    },
    "cotsoc.gen.smic_h_b": {
        "description": "Montant du SMIC horaire brut"
    }
}

```

**Comment by fpagnoux** [comment]
If we dig into `beta.api.openfisca.fr/parameter/rsa.montant_de_base_du_rsa`:

```json
{
    "id": "prestations.minima_sociaux.rsa.montant_de_base_du_rsa",
    "description": "Montant de base du rsa socle",
    "type": "money-amount",
    "values": [{
        "start": "2016-09-01",
        "value": 535.17
    }, {
        "start": "2016-04-01",
        "value": 524.68
    }, {
        "start": "2015-09-01",
        "value": 524.16
    }],
}
```

Or for instance `beta.api.openfisca.fr/parameter/prestations.minima_sociaux.aspa.age_min`
```json
{
    "id": "prestations.minima_sociaux.aspa.age_min",
    "description": "Age minimal requis pour percevoir l'ASPA",
    "type": "age",
    "values": [{
        "start": "2002-01-01",
        "stop": "2014-03-31",
        "value": 65
    }],
}
```

**Comment by cbenz** [comment]
Should we keep IDs like `a.b.c` (ie `prestations.minima_sociaux.aspa.age_min`) or split by `.` like so:

`beta.api.openfisca.fr/parameter/bouclier_fiscal/taux`:

```json
{
    "id": "taux",
    "description": "Taux d'imposition maximal (bouclier fiscal)",
    "type": "rate",
    "values": [
    {
        "stop": "2010-12-31"
    }, {
        "start": "2007-01-01",
        "value": 0.5,
    }, {
        "start": "2006-01-01",
        "value": 0.6
    }],
}
```

**Comment by fpagnoux** [comment]
Some questions : 

#### Should we keep the `type` property ? 

The only concret use I see is formatting (`5 %` vs `1 000 €`)

It's a mix of the previous properties `unit` (that could be `year` or `currency`) and `format` (that could be `float`, `rate`, or`integer`). 

The possible values I kept for `type` are `rate`, `age`, `money-amount`. It seems to cover most of the cases. For other marginal cases, I suggest not setting any `type`.

The subtleties of defining a typology of parameters makes me wonder if the `type` it's worth it 🤔.

#### Which data structure for outdated parameters ?

I found it repetitive to always write both the `start` and `stop` dates for a value (as the stop date is usually the next start date minus one day). This raises the question of obsolete parameters:

In exemple 6, the parameter is obsolete since `2011-01-01`. I put the `stop-date` as a root property. Do you see a better option ?

**Comment by fpagnoux** [comment]
As for the country package metadata, I'd suggest a `country-package` custom header.

**Comment by fpagnoux** [comment]
@MattiSG @cbenz opinions are welcome.

**Comment by fpagnoux** [comment]
>Should we keep IDs like `a.b.c` (ie `prestations.minima_sociaux.aspa.age_min`) or split by `.` like so:
>
>`beta.api.openfisca.fr/parameter/bouclier_fiscal/taux`:

To me this would give too much importance to the xml hierarchy, which we know doesn't work great.

**Comment by fpagnoux** [comment]
New proposition for start/stop dates: 

```json
{
    "id": "bouclier_fiscal.taux",
    "description": "Taux d'imposition maximal (bouclier fiscal)",
    "type": "rate",
    "values": [
    {
        "from": "2011-01-01",
        "value": null
    }, {
        "from": "2007-01-01",
        "value": 0.5
    }, {
        "from": "2006-01-01",
        "value": 0.6
    }],
}
```

To explicit in docs : 
- The from is always included
- The value is always extended till the end of the day preceding the next "from".

**Comment by benjello** [comment]
@fpagnoux : ok with removing the `stop-date` when dates are contiguous. A root `stop date`is sufficient to deal with finishing parameters. A good thing would be to have a root `start_date` when you know that some parameter should have existed but you do not know its exact value.

**Comment by fpagnoux** [comment]
@MattiSG @cbenz  : It seems that adding a `-X` prefix to custom headers [is not considered a good practise anymore](https://tools.ietf.org/html/rfc6648).

**Comment by scenaristeur** [comment]
Bonjour les gars, j'ai un peu décroché sur openfisca ( d'autres projets en cours ) mais pour rappel, si ça peut aider pour vos tests, j'avais mis en place une page pour tester les requêtes vers la webapi : https://pa-comp.firebaseapp.com/bower_components/openfisca-pension/outils/

Bon boulot, en tout cas... Continuez 🙌👏🎉

**Comment by cbenz** [comment]
@scenaristeur Merci ! Dans notre cas il s'agit d'un "endpoint" à l'API qui concerne les paramètres de la législation et non le calcul :)
