### ISSUE TITLE
Add days in logs

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-api#101]
As someone in charge of an openfisca web api instance,
I can see in the logs which day an error has been raised

---------------------

Right now only the time  is logged 😆 

```
12:03:00,221 ERROR [openfisca_core.formulas] An error occurred while calling formula rennes_metropole_transport@individu<2017-03> in module mon_aide
```

**Comment by guillett** [comment]
Just a note:
Log format is specified in *.ini files.

For instance, I submitted a fix for that issue in mes-aides at https://github.com/sgmap/mes-aides-ui/pull/504.

**Comment by MattiSG** [comment]
The flask-based API uses the default gunicorn logger, which does present the days (unsurprisingly).
