### ISSUE TITLE
Move the flask API to the core

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-api#129]
Maintaining version constraints across packages is a nightmare and leads to issues when deploying, as described in https://github.com/openfisca/openfisca-ops/issues/4.

There is no point in pretending that the web API and the core are not coupled, so let's ease maintenance by bundling the API directly with the core.

This concerns only the flask API. The legacy API will stay in this package until it is deprecated.

**Comment by MattiSG** [comment]
- The flask API is to be referred to as a “preview” API until further notice. Its breaking changes will NOT be breaking changes, but only minor changes in the Core until that time.

**Comment by fpagnoux** [comment]
- [ ] Tag pushing works with CI: https://circleci.com/gh/openfisca/openfisca-core/24

**Comment by fpagnoux** [comment]
- [ ] Merge the two packages
- [ ] Update the doc
- [ ] Update the deployment script
