### ISSUE TITLE
Add a "host" option to openfisca-serve

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-web-api#132]
When using the `openfisca-serve` script, I can specify a port but not a host to bind to; the script defaults to `localhost` which is appropriate only in a narrow range of conditions. It will for instance prevent usage from a Docker container, a throwaway virtual machine on a cloud provider, or that home NAS that you use as a server for tinkering with stuff.

Possibly a better default is `0.0.0.0`, a pseudo-host which will result in the server socket binding on every available interface. Alternately, a config option `--host` to override `localhost` is perfectly suitable.

**Comment by fpagnoux** [comment]
Hi @Morendil,

Thanks for using OpenFisca and reaching to us.

As of today, `openfisca-serve` is more suited for local tests than production. It uses a builtin python server which performances are not great.

We recommend to use `gunicorn`, with a proper configuration file such as [this one](https://github.com/sgmap/mes-aides-ui/blob/master/openfisca/api_config.ini).

You can then run your server with the command:

```sh
gunicorn  --paster openfisca/api_config.ini
```

However, if you're interested in running calculations, we are currently working on a new calculation web API and would love to have your feedback on it :).

**Comment by maukoquiroga** [comment]
Hi @Morendil, this repository is now deprecated. Moved to openfisca/openfisca-core#634
