### ISSUE TITLE
Add a status page

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-api#133]
`status.openfisca.fr` should provide users with information about the current availability of the hosted web API instance.
Core maintainers should be notified whenever the API, or some other part of the main OpenFisca subdomains, goes down.

- - - -

Use the beta.gouv.fr pro UptimeRobot account to provide that status page, and double it with a standalone free account for fallback notifications.

**Comment by fpagnoux** [comment]
The status page is here: https://status.openfisca.fr/

Does someone want to check the **2** config on uptime robot before closing the issue ? @sandcha ? @MattiSG ? @Anna-Livia ?

**Comment by fpagnoux** [comment]
@MattiSG should we advertise this page somewhere ?
