### ISSUE TITLE
Include enum members in API endpoint

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-web-api#137]
Some variables are EnumCol (cf. [rsa_non_calculable in legislation explorer](https://legislation.openfisca.fr/rsa_non_calculable) and [rsa_non_calculable code](https://github.com/openfisca/openfisca-france/blob/18.5.1/openfisca_france/model/prestations/minima_sociaux/rsa.py#L865)).

As a user/consumer:
- I would like to have a better understanding of Enum variables in the legislation explorer.
- I would like to know the Enum members via the API.

Currently, I would use those details to validate [a structure in a client application - MesAides](https://github.com/sgmap/mes-aides-ui/blob/master/app/js/constants/droits.js#L156) that add metadata to openfisca variables.

Related to https://github.com/openfisca/legislation-explorer/issues/95.

**Comment by fpagnoux** [comment]
Hi @guillett,

Thanks for reporting this issue, indeed there is much progress to be done with enums, and exposing the value of the operands through the API is something we will consider.

**Comment by fpagnoux** [comment]
As a workaround, today the best way to get the enum members is to click on "Code source de cette variable" on the legislation explorer page. The first lines of the code source of the variable should be the definition of the enum :).

**Comment by oncletom** [comment]
Likewise for `contrat_de_travail` and `categorie_de_salarie`.

**Comment by MattiSG** [comment]
Done via https://github.com/openfisca/openfisca-core/pull/550 :tada:
