### ISSUE TITLE
Installation openfisca-web-api

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#31]
Bonjour,

J'ai installé openfisca-web-api (branche Next) sur un MacBook Pro (OS X Yosemite 10.10.3).

Python 2.7.6

Tout s'est bien passé.

Au moment de lancer le serveur (donc avec la commande "paster serve --reload development-france.ini", j'obtiens les erreurs suivantes, la première étant une erreur d'impotation de _thread from six.moves ;

Voir image ci-dessous. Merci d'avance pour votre aide.

![2015-06-25_12-06-38](https://cloud.githubusercontent.com/assets/1782450/8352087/d66a081e-1b32-11e5-8f13-d15110ae8c65.png)

**Comment by iDevelopper** [comment]
Résolu en réglant la variable d'environnement dans bash_profile.

**Comment by MattiSG** [comment]
Merci pour ces infos @iDevelopper ! Pourrais-tu préciser à quelle valeur as-tu défini `PYTHONPATH` pour faire fonctionner l'installation ?

**Comment by cbenz** [comment]
Cité depuis un email :

> PYTHONPATH="/Users/patrickbodet/Library/Python/2.7/lib/python/site-packages"

**Comment by iDevelopper** [comment]
Bonjour Matti,

PYTHONPATH="/Users/patrickbodet/Library/Python/2.7/lib/python/site-packages"
Export PYTHONPATH

Dans le fichier .bash_profile

 
Cordialement,

Patrick BODET

De :  Matti Schneider <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b247179ac02be5b13b9081b29e4aee559c844842e592cf0000000111a3cc9b9
2a169ce056b4f96@reply.github.com>
Date :  jeudi 25 juin 2015 16:05
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Installation openfisca-web-api (#31)


Merci pour ces infos @iDevelopper <https://github.com/iDevelopper>  !
Pourrais-tu préciser à quelle valeur as-tu défini PYTHONPATH pour faire
fonctionner l'installation ?

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/31#issuecomment-11526
9177> .
