### ISSUE TITLE
Paramètre "decomposition"

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#32]
La présence du paramètre "decomposition" renvoie une erreur sur api-test.openfisca.fr. Fonctionne sur api.openfisca.fr

![test_case](https://cloud.githubusercontent.com/assets/1782450/8449985/a11f6b60-1fd6-11e5-8e8b-60b0037b7822.png)

![resultat](https://cloud.githubusercontent.com/assets/1782450/8450021/f565b328-1fd6-11e5-8893-69659a2c3969.png)

**Comment by cbenz** [comment]
A priori il s'agit d'une mauvaise utilisation du paramètre `decomposition`.

C'est normal vu l'état de la doc (urgence!).

Je pense que ce que tu veux c'est utiliser l'appel `calculate` et non pas `simulate`.

Je reviens vers toi avec un exemple et une doc à jour.

**Comment by iDevelopper** [comment]
Non, simulate avec decomposition, ça fonctionne très bien sur l’api master.

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b27f211b5f0ca4488d3220c13c34ea8f3f80f9f4dd92cf0000000111ad132c9
2a169ce05807a0e@reply.github.com>
Date :  jeudi 2 juillet 2015 16:56
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Paramètre "decomposition" (#32)


A priori il s'agit d'une mauvaise utilisation du paramètre decomposition.

C'est normal vu l'état de la doc (urgence!).

Je pense que ce que tu veux c'est utiliser l'appel calculate et non pas
simulate.

Je reviens vers toi avec un exemple et une doc à jour.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/32#issuecomment-11805
8955> .

**Comment by iDevelopper** [comment]
Le paramètre decomposition n’existe pas dans l’api calculate, n’est-ce pas ?
C’est variables.
 
Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b27f211b5f0ca4488d3220c13c34ea8f3f80f9f4dd92cf0000000111ad132c9
2a169ce05807a0e@reply.github.com>
Date :  jeudi 2 juillet 2015 16:56
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Paramètre "decomposition" (#32)


A priori il s'agit d'une mauvaise utilisation du paramètre decomposition.

C'est normal vu l'état de la doc (urgence!).

Je pense que ce que tu veux c'est utiliser l'appel calculate et non pas
simulate.

Je reviens vers toi avec un exemple et une doc à jour.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/32#issuecomment-11805
8955> .

**Comment by cbenz** [comment]
C'est ça. Je suis en train de documenter cela et de revoir au passage le paramètre decomposition qui semble avoir un bug sur l'API-test en effet.

**Comment by cbenz** [comment]
@iDevelopper un peu d'historique :

* avant il n'y avait que l'appel `simulate` qui prenait un paramètre `decomposition` pouvant être soit le nom du fichier XML à utiliser (parmi https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/decompositions), soit une liste de noms de variables (ce que tu utilises)
* ensuite il y a eu l'appel `calculate` (voir la doc ci-dessous) qui prend un paramètre `variables`, et qui retourne les résultats dispatchés dans une copie du cas type JSON. C'est l'appel qu'utilise l'outil trace (www.openfisca.fr/outils/trace)
* ensuite le paramètre `decomposition` a disparu de l'appel `simulate` pour prendre par défaut `decomp.xml`

La doc que j'ai fait cet après-midi : https://github.com/openfisca/openfisca-web-api/blob/next/endpoints.md

**Comment by cbenz** [comment]
Le commit de suppression du paramètre `decomposition` de l'appel `simulate` : 87b114d192e5d38cdc8223c577a32edd8c03f5cc
