### ISSUE TITLE
Champs non renseignés

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#33]
Bonjour,

`label` n'est pas toujours renseigné (API/1/FIELDS)

Exemple : 

    label = f3sa;
    name = f3sa;

Exemple 2: (vide)

```
field = {
    "@type" = Integer;
    default = 0;
    end = "2009-12-31";
    entity = foy;
    label = "";
    name = f4bl;
}
```

**Comment by cbenz** [comment]
En effet le champ `label` est optionnel. Dans l'idéal il faudrait que toutes les variables disposent d'un label mais il faut donner un peu d'amour à l'existant.

Parfois même le `label` est égal au `name`, ce qui n'est pas souhaitable (il faut mieux une valeur `None`).

J'en ai profité pour améliorer légèrement [l'explorateur de variables](http://legislation.openfisca.fr/variables) pour mieux voir les variables sans label grâce à des warnings en orange, cliquables.

Pareil sur les pages des variables, par exemple http://legislation.openfisca.fr/variables/f3sa

C'est un premier pas en attendant d'outiller plus en profondeur en permettant d'éditer les infos directement depuis cette page, pour soumettre une pull-request github (ce n'est pas pour tout de suite)

Je ferme donc cette issue.
