### ISSUE TITLE
Proposer le champ de saisie "Revenus d'activités"

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#35]
Bonjour,

Branche Next

Pour en revenir sur les revenus, est-il envisageable d'ajouter les revenus d'activités (cases 1AJ, 1BJ, 1CJ, 1DJ) dans le columns_tree (Traitements, salaires, prime pour l'emploi et rentes) ?

**Comment by cbenz** [comment]
@benjello Est-ce pertinent ?

**Comment by benjello** [comment]
Oui c'est pertinent car ce sont des revenus qui apparaissent sur la feuille
d'impôt bien que ce soit des informations individuelles.

**Comment by cbenz** [comment]
Cf openfisca/openfisca-france#280

**Comment by cbenz** [comment]
Rajouter la variable d'entrée [`salaire_imposable_pour_inversion`](https://github.com/openfisca/openfisca-france/blob/3e5dfd22255d0c8ac9d8f89122366e449646d92f/openfisca_france/reforms/inversion_revenus.py#L54) entraîne l'activation de la réforme `inversion_revenus`.

Je ne sais pas encore bien comment ajouter une variable d'entrée appartenant à une réforme à [datatrees.py](https://github.com/openfisca/openfisca-france/blob/3e5dfd22255d0c8ac9d8f89122366e449646d92f/openfisca_france/model/datatrees.py)

À voir avec @eraviart à son retour.

**Comment by iDevelopper** [comment]
Ok, mais ça me paraît logique par rapport à la déclaration de l’impôt sur le
revenus…

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b2a0023f1a42ea5abd19c455ad017e8a7a8b04c2cf92cf0000000111c9f5ac9
2a169ce0595b89c@reply.github.com>
Date :  vendredi 24 juillet 2015 14:46
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Revenus d'activités (#35)


Rajouter la variable d'entrée salaire_imposable_pour_inversion
<https://github.com/openfisca/openfisca-france/blob/3e5dfd22255d0c8ac9d8f891
22366e449646d92f/openfisca_france/reforms/inversion_revenus.py#L54>
entraîne l'activation de la réforme inversion_revenus.

Je ne sais pas encore bien comment ajouter une variable d'entrée appartenant
à une réforme à datatrees.py
<https://github.com/openfisca/openfisca-france/blob/3e5dfd22255d0c8ac9d8f891
22366e449646d92f/openfisca_france/model/datatrees.py>

À voir avec @eraviart <https://github.com/eraviart>  à son retour.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/35#issuecomment-12450
8540> .

**Comment by cbenz** [comment]
Nous sommes bien d'accord sur l'intérêt de la chose, maintenant il faut trouver comment l'intégrer techniquement car la variable fait partie d'une réforme et pour l'instant il n'est pas possible de l'ajouter au `datatrees`. À suivre donc après brainstorming interne.

**Comment by cbenz** [comment]
Nous venons d'en discuter cet après-midi.

Tout d'abord le point d'entrée [`fields`](https://github.com/openfisca/openfisca-web-api/blob/next/docs/endpoints.md#fields) est "deprecated". La raison est qu'il avait été conçu spécifiquement pour le [démonstrateur OpenFisca](http://ui.openfisca.fr/). Modifier les champs proposés pour un simulateur donné revient à modifier cette UI, et inversement; ce qui n'est pas souhaité.

Donc nous conseillons d'utiliser le point d'entrée [`variables`](https://github.com/openfisca/openfisca-web-api/blob/next/docs/endpoints.md#variables), qui exporte la liste complète des variables d'OpenFisca.

À la charge du développeur de choisir les champs qu'il affiche. En l'occurence plusieurs salaires sont retournés par le point d'entrée `variables`, le salaire net, le salaire de base, le salaire imposable. Sachant que pour calculer l'IRPP tu peux utiliser le salaire imposable, libre à toi de l'afficher sous forme de champ de saisie.

En ce qui concerne les catégories (columns tree), sachant qu'il s'agit d'une catégorisation des variables d'entrée réalisée à la main, nous pourrons soit le proposer au téléchargement sous forme de JSON statique, soit tagger chaque variable avec un nom de catégorie (à décider).

Dans cette configuration nous n'avons plus besoin d'activer la réforme sur l'inversion de revenus, car elle ne sert qu'à obtenir le salaire de base de manière approximative, mais celui-ci n'intervient pas dans le calcul de l'impôt, mais des prestations sociales.
En d'autres termes si tu ne demandes pas le calcul du revenu disponible, cela devrait convenir.

Bien entendu je parle sous contrôle de @benjello 

À suivre

**Comment by benjello** [comment]
@iDevelopper  : ce que précise @cbenz est parfaitement correct

**Comment by iDevelopper** [comment]
D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec l'API variables ? 

Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le projet en stand by.

La solution de tagger les variables avec la catégorie serait bien, mais il faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API variables soit trié de manière logique.

J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul de l'impôt n'est pas réalisé.

**Comment by iDevelopper** [comment]
Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

**Comment by cbenz** [comment]
> D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec l'API variables ?

Le démonstrateur utilise toujours `fields` et `field`, et nous ne comptons pas le faire évoluer dans l'instant. Si cela revient dans notre TODO list, nous le porterons en effet vers `varables`.

> Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le projet en stand by.

J'ai créé l'issue https://github.com/openfisca/openfisca-web-api/issues/38

Je vais faire vite :wink:

> La solution de tagger les variables avec la catégorie serait bien, mais il faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API variables soit trié de manière logique.

Pour l'instant on va garder la notion de catégories qui existe.

> J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul de l'impôt n'est pas réalisé.

J'ai créé https://github.com/openfisca/openfisca-france/issues/296

Merci pour ton retour :smile: 

> Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

Il me semble que tu n'en auras pas besoin car si tu souhaites calculer uniquement l'[`IRPP`](http://legislation.openfisca.fr/variables/irpp) (peux-tu confirmer ?) alors il te suffit de demander à l'utilisateur son [`salaire imposable`](http://legislation.openfisca.fr/variables/salaire_imposable).

La réforme d'inversion de revenus permet de passer du salaire imposable au salaire de base, mais de façon approchée. Y a-t-il une autre raison qui te pousserait à vouloir remonter au salaire de base ? Ou bien souhaites-tu calculer par exemple des charges sociales ?

Le fichier [`datatrees.py`](https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0bf30b1fcb888c06b/openfisca_france/model/datatrees.py#L37), qui stocke les catégories dans lesquelles sont rangées les variables d'entrée, connaît uniquement les variables d'entrée. Et la vraie variable d'entrée du point de vue du système socio-fiscal, c'est le salaire de base. Les autres salaires sont calculés, mais comme tu le sais on peut les court-circuiter en leur fournissant une valeur, auquel cas le moteur ne les calcule pas.

Je distingue donc 2 cas :

* Soit tu souhaites seulement calculer l'IRPP, dans ce cas tu changes à chaud la variable `salaire_de_base` en `salaire_imposable`, après avoir téléchargé le JSON depuis ton application.

* Ou alors tu souhaites calculer des charges sociales et dans ce cas, si tu veux, tu actives la réforme d'inversion de revenus comme [documenté ici](https://github.com/openfisca/openfisca-web-api/blob/next/docs/reforms.md#test-if-it-works). Tu devras aussi modifier à chaud la variable `salaire_de_base` en `salaire_imposable` du fait de l'utilisation de la réforme.

Est-ce plus clair ? Je m'attaque aux issues créées pour l'occasion.

**Comment by iDevelopper** [comment]
Il est vrai que je suis plus intéressé par le calcul de l’IRPP et de ses
composantes (nombre de parts, réductions d’impôt, crédits d’impôts,
plafonnements, contributions sociales sur les revenus du capital, etc…),
mais je trouvais intéressant également de pouvoir déterminer le salaire de
base à partir du salaire imposable.

Mais concernant ce dernier point et comme tu le dis, cela ne peut  être
qu’approximatif : un indépendant va cotiser à la RSI, un salarié d’une
entreprise à la sécurité sociale (les taux ne sont pas les mêmes), un
dirigeant ne cotise pas pour les ASSEDIC etc… Donc, plein de cas différents…

Le résultat du test_case est donc souvent faux ou approximatif. Il va
falloir que mon application utilise plutôt l’API calculate que l’API
simulate.

Le calcul de l’IRPP est faux aussi, par exemple : tu saisis un montant de
50000 € dans pensions alimentaires perçues (1AO), le montant de l’impôt est
de 8254 € alors qu’il devrait être de 8249 € . Et il en résulte dans le
démonstrateur des aides de fin d’année (152 €) et du RSA(6167 €)  et donc un
revenu disponible de 48065 €, ce qui ne correspond pas à la réalité. Je ne
pense pas qu’une personne qui perçoit 50000 € de pensions alimentaires
puisse bénéficier de ces aides.

Autre exemple avec 50000 € pour salaire de base : Il en résulte un salaire
imposable de 44490 €. Et un impôt de 5592 €. Alors qu’un salaire imposable
de 44490 € devrait donner un impôt de 7708 €.

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b2f7fc43e62fa9883d55a8f0d2ea6bdb356717e36492cf0000000111fe8bc19
2a169ce0595b89c@reply.github.com>
Date :  mercredi 2 septembre 2015 12:04
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Proposer le champ de saisie "Revenus
d'activités" (#35)

> 
> D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le
> démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec
> l'API variables ?

Le démonstrateur utilise toujours fields et field, et nous ne comptons pas
le faire évoluer dans l'instant. Si cela revient dans notre TODO list, nous
le porterons en effet vers varables.
> 
> Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le
> projet en stand by.

J'ai créé l'issue #38
<https://github.com/openfisca/openfisca-web-api/issues/38>

Je vais faire vite 
> 
> La solution de tagger les variables avec la catégorie serait bien, mais il
> faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API
> variables soit trié de manière logique.

Pour l'instant on va garder la notion de catégories qui existe.
> 
> J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs
> "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul
> de l'impôt n'est pas réalisé.

J'ai créé openfisca/openfisca-france#296
<https://github.com/openfisca/openfisca-france/issues/296>

Merci pour ton retour
> 
> Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si
> la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

Il me semble que tu n'en auras pas besoin car si tu souhaites calculer
uniquement l'IRPP <http://legislation.openfisca.fr/variables/irpp>  (peux-tu
confirmer ?) alors il te suffit de demander à l'utilisateur son salaire
imposable <http://legislation.openfisca.fr/variables/salaire_imposable> .

La réforme d'inversion de revenus permet de passer du salaire imposable au
salaire de base, mais de façon approchée. Y a-t-il une autre raison qui te
pousserait à vouloir remonter au salaire de base ? Ou bien souhaites-tu
calculer par exemple des charges sociales ?

Le fichier datatrees.py
<https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0
bf30b1fcb888c06b/openfisca_france/model/datatrees.py#L37> , qui stocke les
catégories dans lesquelles sont rangées les variables d'entrée, connaît
uniquement les variables d'entrée. Et la vraie variable d'entrée du point de
vue du système socio-fiscal, c'est le salaire de base. Les autres salaires
sont calculés, mais comme tu le sais on peut les court-circuiter en leur
fournissant une valeur, auquel cas le moteur ne les calcule pas.

Je distingue donc 2 cas :
* 
* Soit tu souhaites seulement calculer l'IRPP, dans ce cas tu changes à
chaud la variable salaire_de_base en salaire_imposable, après avoir
téléchargé le JSON depuis ton application.
* 
* Ou alors tu souhaites calculer des charges sociales et dans ce cas, si tu
veux, tu actives la réforme d'inversion de revenus comme documenté ici
<https://github.com/openfisca/openfisca-web-api/blob/next/docs/reforms.md#te
st-if-it-works> . Tu devras aussi modifier à chaud la variable
salaire_de_base en salaire_imposable du fait de l'utilisation de la réforme.

Est-ce plus clair ? Je m'attaque aux issues créées pour l'occasion.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/35#issuecomment-13701
1169> .

**Comment by iDevelopper** [comment]
Autre précision, s’il te plait :

Le salaire imposable pour vous est-il déjà déduit de l’abattement des 10%
lorsqu’on est au forfait et non aux frais réels ?


Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b2f7fc43e62fa9883d55a8f0d2ea6bdb356717e36492cf0000000111fe8bc19
2a169ce0595b89c@reply.github.com>
Date :  mercredi 2 septembre 2015 12:04
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Proposer le champ de saisie "Revenus
d'activités" (#35)

> 
> D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le
> démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec
> l'API variables ?

Le démonstrateur utilise toujours fields et field, et nous ne comptons pas
le faire évoluer dans l'instant. Si cela revient dans notre TODO list, nous
le porterons en effet vers varables.
> 
> Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le
> projet en stand by.

J'ai créé l'issue #38
<https://github.com/openfisca/openfisca-web-api/issues/38>

Je vais faire vite 
> 
> La solution de tagger les variables avec la catégorie serait bien, mais il
> faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API
> variables soit trié de manière logique.

Pour l'instant on va garder la notion de catégories qui existe.
> 
> J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs
> "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul
> de l'impôt n'est pas réalisé.

J'ai créé openfisca/openfisca-france#296
<https://github.com/openfisca/openfisca-france/issues/296>

Merci pour ton retour
> 
> Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si
> la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

Il me semble que tu n'en auras pas besoin car si tu souhaites calculer
uniquement l'IRPP <http://legislation.openfisca.fr/variables/irpp>  (peux-tu
confirmer ?) alors il te suffit de demander à l'utilisateur son salaire
imposable <http://legislation.openfisca.fr/variables/salaire_imposable> .

La réforme d'inversion de revenus permet de passer du salaire imposable au
salaire de base, mais de façon approchée. Y a-t-il une autre raison qui te
pousserait à vouloir remonter au salaire de base ? Ou bien souhaites-tu
calculer par exemple des charges sociales ?

Le fichier datatrees.py
<https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0
bf30b1fcb888c06b/openfisca_france/model/datatrees.py#L37> , qui stocke les
catégories dans lesquelles sont rangées les variables d'entrée, connaît
uniquement les variables d'entrée. Et la vraie variable d'entrée du point de
vue du système socio-fiscal, c'est le salaire de base. Les autres salaires
sont calculés, mais comme tu le sais on peut les court-circuiter en leur
fournissant une valeur, auquel cas le moteur ne les calcule pas.

Je distingue donc 2 cas :
* 
* Soit tu souhaites seulement calculer l'IRPP, dans ce cas tu changes à
chaud la variable salaire_de_base en salaire_imposable, après avoir
téléchargé le JSON depuis ton application.
* 
* Ou alors tu souhaites calculer des charges sociales et dans ce cas, si tu
veux, tu actives la réforme d'inversion de revenus comme documenté ici
<https://github.com/openfisca/openfisca-web-api/blob/next/docs/reforms.md#te
st-if-it-works> . Tu devras aussi modifier à chaud la variable
salaire_de_base en salaire_imposable du fait de l'utilisation de la réforme.

Est-ce plus clair ? Je m'attaque aux issues créées pour l'occasion.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/35#issuecomment-13701
1169> .

**Comment by iDevelopper** [comment]
OK pour les catégories, mais dans le tree, je n’ai pas vu les variables qui
concernent les « Revenus de capitaux mobiliers ». Tu pourras me dire quand
vous aurez opté pour le tag des variables ou pour un JSON différent ?

Patrick BODET
O
De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b2f7fc43e62fa9883d55a8f0d2ea6bdb356717e36492cf0000000111fe8bc19
2a169ce0595b89c@reply.github.com>
Date :  mercredi 2 septembre 2015 12:04
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Proposer le champ de saisie "Revenus
d'activités" (#35)

> 
> D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le
> démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec
> l'API variables ?

Le démonstrateur utilise toujours fields et field, et nous ne comptons pas
le faire évoluer dans l'instant. Si cela revient dans notre TODO list, nous
le porterons en effet vers varables.
> 
> Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le
> projet en stand by.

J'ai créé l'issue #38
<https://github.com/openfisca/openfisca-web-api/issues/38>

Je vais faire vite 
> 
> La solution de tagger les variables avec la catégorie serait bien, mais il
> faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API
> variables soit trié de manière logique.

Pour l'instant on va garder la notion de catégories qui existe.
> 
> J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs
> "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul
> de l'impôt n'est pas réalisé.

J'ai créé openfisca/openfisca-france#296
<https://github.com/openfisca/openfisca-france/issues/296>

Merci pour ton retour
> 
> Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si
> la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

Il me semble que tu n'en auras pas besoin car si tu souhaites calculer
uniquement l'IRPP <http://legislation.openfisca.fr/variables/irpp>  (peux-tu
confirmer ?) alors il te suffit de demander à l'utilisateur son salaire
imposable <http://legislation.openfisca.fr/variables/salaire_imposable> .

La réforme d'inversion de revenus permet de passer du salaire imposable au
salaire de base, mais de façon approchée. Y a-t-il une autre raison qui te
pousserait à vouloir remonter au salaire de base ? Ou bien souhaites-tu
calculer par exemple des charges sociales ?

Le fichier datatrees.py
<https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0
bf30b1fcb888c06b/openfisca_france/model/datatrees.py#L37> , qui stocke les
catégories dans lesquelles sont rangées les variables d'entrée, connaît
uniquement les variables d'entrée. Et la vraie variable d'entrée du point de
vue du système socio-fiscal, c'est le salaire de base. Les autres salaires
sont calculés, mais comme tu le sais on peut les court-circuiter en leur
fournissant une valeur, auquel cas le moteur ne les calcule pas.

Je distingue donc 2 cas :
* 
* Soit tu souhaites seulement calculer l'IRPP, dans ce cas tu changes à
chaud la variable salaire_de_base en salaire_imposable, après avoir
téléchargé le JSON depuis ton application.
* 
* Ou alors tu souhaites calculer des charges sociales et dans ce cas, si tu
veux, tu actives la réforme d'inversion de revenus comme documenté ici
<https://github.com/openfisca/openfisca-web-api/blob/next/docs/reforms.md#te
st-if-it-works> . Tu devras aussi modifier à chaud la variable
salaire_de_base en salaire_imposable du fait de l'utilisation de la réforme.

Est-ce plus clair ? Je m'attaque aux issues créées pour l'occasion.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/35#issuecomment-13701
1169> .

**Comment by iDevelopper** [comment]
Si, pardon, c’est dans Déclaration d’impôt…

Patrick BODET

De :  Christophe Benz <notifications@github.com>
Répondre à :  openfisca/openfisca-web-api
<reply+001b32b2f7fc43e62fa9883d55a8f0d2ea6bdb356717e36492cf0000000111fe8bc19
2a169ce0595b89c@reply.github.com>
Date :  mercredi 2 septembre 2015 12:04
À :  openfisca/openfisca-web-api <openfisca-web-api@noreply.github.com>
Cc :  Patrick BODET <patrick.bodet4@wanadoo.fr>
Objet :  Re: [openfisca-web-api] Proposer le champ de saisie "Revenus
d'activités" (#35)

> 
> D'accord, j'utilisais l'api fields et columns_tree. Est-ce que le
> démonstrateur utilise encore cette api ? Si oui, allez vous le ré-écrire avec
> l'API variables ?

Le démonstrateur utilise toujours fields et field, et nous ne comptons pas
le faire évoluer dans l'instant. Si cela revient dans notre TODO list, nous
le porterons en effet vers varables.
> 
> Donc dans l'immédiat je ne peux rien faire sans les catégories sinon mettre le
> projet en stand by.

J'ai créé l'issue #38
<https://github.com/openfisca/openfisca-web-api/issues/38>

Je vais faire vite 
> 
> La solution de tagger les variables avec la catégorie serait bien, mais il
> faudrait aussi ajouter une notion de tri ou que le JSON retourné par l'API
> variables soit trié de manière logique.

Pour l'instant on va garder la notion de catégories qui existe.
> 
> J'ai testé autre chose avec le démonstrateur : Si on renseigne les champs
> "Autres revenus imposables (1AP)" ou "Pensions, retraites ...(1AS)", le calcul
> de l'impôt n'est pas réalisé.

J'ai créé openfisca/openfisca-france#296
<https://github.com/openfisca/openfisca-france/issues/296>

Merci pour ton retour
> 
> Pourrait-on imaginer d'envoyer un paramètre dans le test_case qui indique si
> la réforme sur l'inversion des revenus est souhaitée ou non, tout simplement ?

Il me semble que tu n'en auras pas besoin car si tu souhaites calculer
uniquement l'IRPP <http://legislation.openfisca.fr/variables/irpp>  (peux-tu
confirmer ?) alors il te suffit de demander à l'utilisateur son salaire
imposable <http://legislation.openfisca.fr/variables/salaire_imposable> .

La réforme d'inversion de revenus permet de passer du salaire imposable au
salaire de base, mais de façon approchée. Y a-t-il une autre raison qui te
pousserait à vouloir remonter au salaire de base ? Ou bien souhaites-tu
calculer par exemple des charges sociales ?

Le fichier datatrees.py
<https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0
bf30b1fcb888c06b/openfisca_france/model/datatrees.py#L37> , qui stocke les
catégories dans lesquelles sont rangées les variables d'entrée, connaît
uniquement les variables d'entrée. Et la vraie variable d'entrée du point de
vue du système socio-fiscal, c'est le salaire de base. Les autres salaires
sont calculés, mais comme tu le sais on peut les court-circuiter en leur
fournissant une valeur, auquel cas le moteur ne les calcule pas.

Je distingue donc 2 cas :
* 
* Soit tu souhaites seulement calculer l'IRPP, dans ce cas tu changes à
chaud la variable salaire_de_base en salaire_imposable, après avoir
téléchargé le JSON depuis ton application.
* 
* Ou alors tu souhaites calculer des charges sociales et dans ce cas, si tu
veux, tu actives la réforme d'inversion de revenus comme documenté ici
<https://github.com/openfisca/openfisca-web-api/blob/next/docs/reforms.md#te
st-if-it-works> . Tu devras aussi modifier à chaud la variable
salaire_de_base en salaire_imposable du fait de l'utilisation de la réforme.

Est-ce plus clair ? Je m'attaque aux issues créées pour l'occasion.

—
Reply to this email directly or view it on GitHub
<https://github.com/openfisca/openfisca-web-api/issues/35#issuecomment-13701
1169> .

**Comment by MattiSG** [comment]
Cette issue concernait principalement `openfisca-france`.

Les éléments spécifiquement liés à l'API ont près de 3 ans, et il n'y a pas eu de mouvement depuis. Je ferme.

@iDevelopper n'hésite pas rouvrir de nouvelles issues en mentionnant celle-ci si certains des problèmes sont toujours d'actualité.
