### ISSUE TITLE
Different results between calculate and simulate endpoints

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#37]
There is a difference between `calculate` and `simulate` endpoints for the same test case.

The next step to solve this issue is to develop a [decomposition](https://github.com/openfisca/openfisca-france/blob/next/openfisca_france/decompositions/decomp.xml) checker which guarantees that the sums of the aggregated nodes equals the calculated variable with the same name.

For exemple the [`psoc`](https://github.com/openfisca/openfisca-france/blob/a3772aef8b5e58876205b6c0bf30b1fcb888c06b/openfisca_france/decompositions/decomp.xml#L83-L116) node aggregates 3 sub-nodes (`pfam`, `mini` and `aides_logement`), and the variable [`psoc`](http://legislation.openfisca.fr/variables/psoc) sums the same 3 variables.

That's correct but this could have been wrong if `decomp.xml` was false.

**Comment by benjello** [comment]
+1

**Comment by cbenz** [comment]
@benjello abolutely

**Comment by cbenz** [comment]
Issue already exists https://github.com/openfisca/openfisca-france/issues/281

Holidays made me forget about it :smile:

**Comment by MattiSG** [comment]
What about just consolidating the two APIs in a single, tested one…? I’m afraid of overengineering and trying to rigidify an unstable existing solution.

**Comment by cbenz** [comment]
This is on my TODO list and now it's an issue #39
