### ISSUE TITLE
Extract columns_tree endpoint from deprecated fields endpoint

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#38]
Create a new endpoint named `categories` which returns the contents of the [`datatrees.py`](https://github.com/openfisca/openfisca-france/blob/next/openfisca_france/model/datatrees.py) file, using the JSON-ification used by this [OpenFisca-Parsers script](https://github.com/openfisca/openfisca-parsers/blob/bc46cdcf0f49b5fa9537dc571799287e1933d6b9/openfisca_parsers/scripts/datatrees_to_json.py#L45-L48).

**Comment by MattiSG** [comment]
No movement in 2.5 years. Any such change should be made after a considerate global API design. Closing.
