### ISSUE TITLE
Remove "google styleguide" JSON data

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#41]
In general try to remove in the JSON output data that is already in the input.

In particular these keys: `context`, `params`, `method`, `apiVersion`

**Comment by cbenz** [comment]
@MattiSG what do you think about the removal of [`apiVersion`](https://github.com/openfisca/openfisca-france/blob/0133e9343e4fa4c4e9335f841e5760721bacc86e/openfisca_france/reforms/aides_ville_paris.py#L346) keys?

**Comment by MattiSG** [comment]
That question is a bit vague  ;)

I think it's always good to have some kind of reference to a description of the representation within the representation itself, for introspection. Thus, if `apiVersion` was an actually useful reference to some documented state of the code, it would be great to keep it.
At the moment, though, I don't think proper versioning has been enforced in OpenFisca, and that piece of infirmation is thus misleading.

If versioning information was to be stored in the output data, then I don't think a single version number would fit. Considering OpenFisca's architecture, it would probably be an object with version identifiers for each of the parts (Core, Parsers, France, API), as a change in any of those can change the output.
At least that's the consideration that made me create the [submodule wrapper](https://github.com/sgmap/openfisca) we use to ensure known stable points are reproducible.

**Comment by MattiSG** [comment]
Don't invest in the current endpoints if there's no user request.
