### ISSUE TITLE
Uncalculated variables

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#43]
This variables are not calculated for the year 2014

reductions
credits_impot

**Comment by benjello** [comment]
There are yet to be updated but you can help if you want ;-)
You can these [informations] (http://vosdroits.service-public.fr/particuliers/R1281.xhtml) to complete the model for year 2014.

Here is what is need to be done:
 - [ ] the réductions and crédits d'impôts which formula didn't change 
   - [ ] list them and extend them to 2014
   - [ ]  check if the values of the parameters didn't change and update them if needed
 - [ ] the new réductions and crédits d'impôts or those which formula didn't change
  - [ ] list them and provide references (fiche de calcul, notice de etc)
  - [ ] implement them

**Comment by iDevelopper** [comment]
I would like to help but my knowledge of Python is null and I master very badly Github !

**Comment by benjello** [comment]
You can do the listing part which do not require no coding skills ;-)

**Comment by cbenz** [comment]
@iDevelopper and I have to learn to understand the legislation ;-)

**Comment by cbenz** [comment]
Since this is not a web API issue, I move it to openfisca/openfisca-france

**Comment by cbenz** [comment]
This issue was moved to openfisca/openfisca-france#320
