### ISSUE TITLE
Add variables to simulate API endpoint

### ISSUE THREAD

**Issue by iDevelopper** [openfisca/openfisca-web-api#44]
Is it possible to add the variables nbptr, reductions, credits_impot in the returned JSON?

**Comment by MattiSG** [comment]
This issue is 2.5 years old and was not treated. Future users: please see [the web API documentation](https://doc.openfisca.fr/openfisca-web-api/endpoints.html).

@iDevelopper feel free to reply if this question is still relevant to you.

**Comment by iDevelopper** [comment]
Il n'y a pas eu de réponse.

**Comment by MattiSG** [comment]
@iDevelopper Oui, j'en suis bien conscient et j'en suis désolé. Est-il encore pertinent d'en apporter une aujourd'hui ?

**Comment by iDevelopper** [comment]
Personnellement, j'avais mis mon projet en stand by car des calculs restaient très largement faux. Voir #35, si tu as le courage de tout relire.
