### ISSUE TITLE
ParameterNotFound

### ISSUE THREAD

**Issue by laem** [openfisca/openfisca-web-api#48]
It looks like web-api/master refers to code from -core/better-error-messages, which breaks the web server. 
@cbenz 
It seems to be working fine after a master rebase in better-error-messages.

**Comment by fpagnoux** [comment]
+1, same problem here, I can't update openfisca for mes-aides :(
IMO this calls once again for a better dependency management system as discussed in [#380](https://github.com/openfisca/openfisca-france/issues/380)

**Comment by cbenz** [comment]
You're right,  I merged the branch `better-error-messages` in `master` on Core, it was a mistake.
