### ISSUE TITLE
Calcul du RSA

### ISSUE THREAD

**Issue by scenaristeur** [openfisca/openfisca-web-api#68]
Bonjour

Bonjour, pour le projet Pa-Comp, j'ai besoin d'obtenir le montant du RSA.
Lors du calcul, j'obtiens les valeurs suivantes : 
RSA personne seule : le calcul du RSA semble fonctionner pour une personne seule  : https://jsbin.com/hotiko/edit?js,console, d'après les informations présentes sur service-public : https://www.service-public.fr/particuliers/vosdroits/N19775

Il manque juste la réévaluation à partir de septembre 2016 (535 €au lieu de 525 € )
idem pour un couple (787 € au lieu de 802 € : https://jsbin.com/namenub/edit?js,console)

Par contre, dès que j'ajoute un en fant (https://jsbin.com/sokuqo/edit?js,console), j**'obtiens 695 € et je ne vois pas à quoi cela correspond.**
dois-je utiliser "rsa_majore" comme variable de sortie ? j'ai testé, mais je ne dois pas avoir les bonnes variables en entrée, et obtiens un message d'erreur.
Pourriez-vous m'éclairer ? merci

**Comment by benjello** [comment]
La mise à jour est [dans les tuyaux](https://github.com/openfisca/openfisca-france/pull/579).
Le 695 doit venir du fait que l'on suppose que le parent est isolé.
Mais @fpagnoux te renseignera mieux que moi.
N'hésite aps à regarder les [tests](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/tests), ils peuvent te donner des idées.

**Comment by fpagnoux** [comment]
Une personne seule avec un enfant qui ne perçoit pas de pension alimentaire a droit à l'ASF (allocation de soutien familiale, 105€ environ).
Cet ASF est en partie déduit du montant du RSA (91€ par enfant bénéficiaire).
Il est donc normal que le montant du RSA soit réduit (787 - 91).

**Comment by scenaristeur** [comment]
ok merci pour ces infos, je vois que la correction est en cours. 
Si besoin, pour tester les requetes vers l'API Web, j'ai mis en place un petit outil javascript grâce auquel on peut modifier le JSON envoyé : https://github.com/scenaristeur/Pa-Comp/tree/master/public/outils

**Comment by MattiSG** [comment]
Merci pour cette référence @scenaristeur !

#579 ayant été intégrée, je ferme cette issue.
