### ISSUE TITLE
Support any country

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-api#76]
As a Producer from a new country,
I can use the `web-api` to expose the formulas I add,
So that they can be computed over HTTP

- - - -

The web api didn't work out of the box for openfisca Senegal.

**Comment by fpagnoux** [comment]
1st problem
------------

There is a reference to the `TaxBenefitSystem` attribute `DECOMP_DIR`. A default `TBS` doesn't have such an attribute.

I understand the basic concept of a decomposition, but not everything. For instance, some decomposition node have a `color` attribute. Is it styling for the UI ?

**Comment by benjello** [comment]
Yes it is.

**Comment by fpagnoux** [comment]
Are the `decompositions` xml files automatically generated ?

**Comment by fpagnoux** [comment]
Ok. There are some big issues with decompositions (style elements in a country package, copy paste of variables labels in description, logic repetition) but it is too big to deal with now. I will just find a workaround.

**Comment by fpagnoux** [comment]
2nd problem
-------------

Some general business (such as parsing the periods) is done in `make_json_or_python_to_test_case` in france country package.

**Comment by fpagnoux** [comment]
Wooo finished, that was a big block !
