### ISSUE TITLE
Export the GitHub repository URL

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#77]
As a web application developer,
I can know the URL of the GitHub repository corresponding to the country package served by the API,
So that I can create links to files referenced by relative paths in /api/1/variables endpoint

**Comment by cbenz** [comment]
For now some web apps hardcode the value ([example](https://github.com/openfisca/legislation-explorer/blob/7598d1218bb3ebf69d06160624c752c2033eaea5/config/production.france.js#L6))

**Comment by MattiSG** [comment]
Could be useful when / if the legislation explorer becomes international. That's not currently the case, and no one else asked for this.
