### ISSUE TITLE
Document the actual production deploy method

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#83]
This [section of `README.md`](https://github.com/openfisca/openfisca-web-api/blob/master/README.md#deploy-in-production) is wrong.

Today we deploy with nginx which reverse-proxifies to [gunicorn](http://gunicorn.org/).

- [x] commit a production directory with template files
- [x] move the README.md section to `production/README.md`

**Comment by MattiSG** [comment]
Duplicate of #82.
