### ISSUE TITLE
Remove dependency to OpenFisca-France

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#90]
OpenFisca-Web-API package should serve any country, thus it should not express any constraint to OpenFisca-France like it is [on this line](https://github.com/openfisca/openfisca-web-api/blob/d790243123c72fd198cc29a63d6dd4dedb316510/setup.py#L49).

The thing is the Web API works with OpenFisca-France == 13.1.1 on https://legislation.openfisca.fr/
If we run the whole tests many will fail, but that's only those on deprecated features (`field` and `graph` endpoints)

Now what about removing this dependency constraint and create the right abstractions?
From an architectural point of view it seems to me the right thing to do.

Any thoughts @openfisca/coreteam?

**Comment by MattiSG** [comment]
Yes, that's definitely [the right thing to do](https://github.com/openfisca/openfisca-web-api/pull/92#issuecomment-283333468), would it be only to avoid work like #92.

But this is an internal refactor that will have to be prioritised at some later stage :wink:

**Comment by fpagnoux** [comment]
This dependency has already been removed I think. @cbenz can you close the issue if it's the case ? Thanks !

**Comment by cbenz** [comment]
Yes: https://github.com/openfisca/openfisca-web-api/pull/92/files#diff-2eeaed663bd0d25b7e608891384b7298L48
