### ISSUE TITLE
Allow changing README without version bump

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#94]
Specifically on this repository, it seems that the feature that exists on Core, which allows to edit non-Python-package files without bumping the version number, is not enabled.

@fpagnoux Can you confirm you did that on Core only?

See https://github.com/openfisca/openfisca-core/commit/19ca49b42d54415eb0e13c8f85a225e65c85435c

**Comment by fpagnoux** [comment]
I confirm this was done on core only, and that we should spread it to other repositories.
